steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/carracer
      - --cache=true
      - --cache-ttl=10000h
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 50000s