apiVersion: v1
kind: Pod
metadata:
  name: "carracer"
spec:
  containers:
    - name: "carracer"
      image: "gcr.io/overwatch-analysis/carracer"
      command: ["sleep"]
      args: ["100000"]
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    cloud.google.com/gke-local-ssd: "true"